version: '3'

services:

  selenium:
    container_name: selenium
    environment:
    - START_XVFB=false
    image: selenium/standalone-chrome

  snmpd:
    container_name: snmpd
    depends_on:
    - selenium
    volumes:
    - ./examples/example-chrome-selenium.py:/example-chrome-selenium.py
    - ./examples/example-chrome-snmpd.conf:/etc/snmp/snmpd.conf
    image: kedu/selenium-python-snmpd

  test:
    container_name: test
    depends_on:
    - selenium
    - snmpd
    image: kedu/selenium-python-snmpd
